Azure/iot-plugandplay-models

.github/workflows/push_expanded_to_storage.yml, .github/workflows/validate-models.yml
=> Update to Azure GitHub package feed

README.md, package.json
https://github.com/Azure/iot-plugandplay-models-tools/issues/81
=> Rename repo name

dtmi/com/example/temperaturecontroller-1.json, dtmi/com/example/thermostat-1.json
Thank you for contributing to the Device Models repository!
This checklist is used to make sure that common guidelines for a pull request are followed.
- [x ] The pull request **only** contains device model documents?
- [ x] All device models are in JSON-LD format?
- [ x] One device model per file?
- [ x] A `@context` property at the root of the DTDL document specifying the DTDL version ("dtmi:dtdl:context;2")?
- [ x] One `@id` property specified at the root of …
=> initial sample models added

CODEOWNERS, dtmi/com/microchip/pic_iot_wm-1.json
Thank you for contributing to the Device Models repository!
This checklist is used to make sure that common guidelines for a pull request are followed.
/c @randywu763
=> Add dtmi:com:Microchip:PIC_IoT_WM;1

dtmi/benq/product/ifp_cp_series-1.json, dtmi/benq/product/ops_ie_series-1.json, dtmi/benq/product/runtimeinfo-1.json
+ Add ifp_cp_series, ops_ie_series, and runtimeInfo 3 interfaces (DTDLv2)
+ for  Azure IoT PnP preview-refresh certification
=> Add interfaces of BenQ interface

dtmi/advantech/epc_t4286-1.json
Add Advantech interface epc_t4286-1.json for Pnp certification.
=> Add Advantech interface epc_t4286-1.json

dtmi/uk/co/clearwatercontrols/akp-1.json, dtmi/uk/co/clearwatercontrols/akp/properties-1.json, dtmi/uk/co/clearwatercontrols/configurationcommands-1.json, dtmi/uk/co/clearwatercontrols/deraggerplus/commands-1.json, dtmi/uk/co/clearwatercontrols/deraggerplus/telemetry-1.json, dtmi/uk/co/clearwatercontrols/pumpcommands-1.json
Local verification was successful (;
=> Add Clearwater Controls Advanced Keypad and required components

dtmi/bosch/xdk110-1.json
Add the interface for the Bosch XDK110
=> Add Bosch interface xdk110-1.json for the Bosch XDK110 Device

dtmi/com/example/azuresphere/labmonitor-1.json
For use with Azure Sphere and IoT Central Microsoft Learn Module
=> Azure Sphere Lab Monitor Model

dtmi/seeedkk/wioterminal/wioterminal_aziot_example-2.json
=> Add wioterminal_aziot_example;2

.azure-devops/sync.yml, .gitignore
Eventual consistency/sync baseline
=> Provides sync baseline

dtmi/realtek/rtk_ameba_series-1.json, dtmi/realtek/rtk_audio-1.json, dtmi/realtek/rtk_bluetooth-1.json, dtmi/realtek/rtk_device_info-1.json, dtmi/realtek/rtk_gpio-1.json, dtmi/realtek/rtk_lcd-1.json, dtmi/realtek/rtk_memory-1.json, dtmi/realtek/rtk_system-1.json, dtmi/realtek/rtk_video-1.json, dtmi/realtek/rtk_wireless-1.json
* Create dtmi/realtek/rtk_ameba_series-1.json
* Create dtmi/realtek/rtk_audio-1.json
* Create dtmi/realtek/rtk_bluetooth-1.json
* Create dtmi/realtek/rtk_device_info-1.json
* Create dtmi/realtek/rtk_gpio-1.json
* Create dtmi/realtek/rtk_lcd-1.json
* Create dtmi/realtek/rtk_memory-1.json
* Create dtmi/realtek/rtk_system-1.json
* Create dtmi/realtek/rtk_video-1.json
* Create dtmi/realtek/rtk_wireless-1.json
The repository pipeline will ensure minimum validation of …
=> Realtek add Ameba series devices

.github/pull_request_template.md
Fix typo for PnP term in the PR template
=> rename pnp term

dtmi/avnet/starterkit-1.json
- Avnet
- avnet.com
- https://github.com/Avnet
- [Avnet Azure Sphere Starter Kit](http://avnet.me/mt3620-kit)
- Azure Sphere MCU
- Azure Sphere SDK
- Demo applications for Azure Sphere Workshop students
- @bawilless
=> Add Avnet Starter Kit Model

dtmi/seeedkk/wioterminal/wioterminal_aziot_example-2.json, dtmi/seeedkk/wioterminal/wioterminal_aziot_example-3.json
=> [seeedkk] Add unit of accelX, accelY and accelZ

dtmi/sysinno/iaeris1-1.json
- Company name: Sysinno Technology Inc.
- Company website : [https://www.sysinnotec.com/ehomepage](https://www.sysinnotec.com/ehomepage)
- Product pdf : [iAeris Indoor Air Quality Detector PDF](https://ac1f3ec5-3a86-4c35-9d2e-c0d4f323d127.filesusr.com/ugd/2f33a0_a7abe4d205c24ef995e6d5b4cc446ab6.pdf)
- MCU: Azure sphere 
- Custom solution
@Lin-YenYu-sysinno
=> Add sysinno Air Quality Detector

dtmi/advantech/ark_1124-1.json, dtmi/advantech/ds_580-1.json, dtmi/advantech/eis_d110-1.json, dtmi/advantech/eis_d620-1.json, dtmi/advantech/eis_s230-1.json
- Company name: Advantech
- Company website: https://www.advantech.com/
- GitHub presence: https://github.com/ADVANTECH-Corp/
- Product website: https://www.advantech.tw/products/b5f4309c-1827-4a8f-9855-3b0324c446bb/ds-580/mod_f7a4b28e-63e3-48bc-9c68-f02093065b55
- Product website: https://www.advantech.com/products/1-2jkbyz/ark-1124/mod_98b0cd9c-ee56-45df-ace8-17ab10311242
- Product website: https://www.advantech.com/products/071c0784-5e9b-4bb8-bb07-2cb06da757a1/eis-d110/mod_11993927-0038-4150-94c7-5c4b489c2442
- Product website:https://www.advantech.com/products/071c0784-5e9b-4bb8-bb07-2cb06da757a1/eis-d620/mod_e512eee7-c3f3-4acb-9a07-a435140143f3
- Product website:https://www.advantech.com/products/071c0784-5e9b-4bb8-bb07-2cb06da757a1/eis-s230/mod_cf3cc4d6-4f20-4585-aba2-50d7336b9da9
- …
=> Add advantech interfaces

dtmi/seeedkk/wioterminal/wioterminal_aziot_example-4.json
=> [seeedkk] Add rightButton, centerButton, leftButton

dtmi/ust/tagu310-1.json
=> tagu310model

dtmi/himax/weiplus-1.json
- Himax
- https://www.himax.com.tw/
- https://github.com/HimaxSPD/iot-plugandplay-models
> Info identifying your PnP device.
- WE-I Plus (Human presence)
-  Synopsys EM9D with Azure RTOS
- azure sdk for c 
> Info related to broader PnP goals.  
- https://devicecatalog.azure.com/
- IoT Edge Device
- Custom solution
- @HimaxSPD
=> Add Himax dtmi model

dtmi/avcon/cs1950-1.json
Avcon
http://www.avcon.com.cn/
AVCON-CS1950
http://www.avcon.com.cn/product/detail.aspx?id=6
=> Add AVCON-CS1950 model.

dtmi/seeedkk/wioterminal/wioterminal_aziot_example-5.json
=> [seeedkk] Add description

dtmi/mydevicesinc/advantech/wise2410na-1.json, dtmi/mydevicesinc/dragino/lht65-1.json, dtmi/mydevicesinc/globalsat/lt100e_tracker-1.json, dtmi/mydevicesinc/lansitec/solar_bluetooth_gateway-1.json, dtmi/mydevicesinc/ursalink/am100-1.json
- Company name: myDevices, Inc
- Company website: https://mydevices.com
- GitHub presence: https://github.com/myDevicesIoT
Product Information and datasheets available on https://store.mydevices.com
- Dragino LHT60 Temp/Hum Sensor 
- Globalsat LT-501
- Ursalink AM100
- Lansitec BLE Gateway
- Advantech WISE2410
@eptak @jburhenn
=> myDevices Initial DTDLv2 submission

dtmi/aaeon/upsquaredpro-1.json
AAEON
https://www.aaeon.com/tw/
AAEON-UPSquaredPro
https://up-board.org/up-squared-pro/
=> Add AAEON-UPSquaredPro model.

dtmi/adlink/mxc662x2e-1.json
ADLINK
https://www.adlinktech.com/en/index
MXC-662X-2E/M4G
https://www.adlinktech.com/Products/Industrial_PCs_Fanless_Embedded_PCs/ExpandableFanlessEmbeddedComputers/MXC-6600_Series?lang=en
=> Add ADLINK-MXC662X2E model.

dtmi/asus/tinkerboardbasic-1.json
ASUS
https://www.asus.com/tw/
Tinker Board
https://www.asus.com/tw/Single-Board-Computer/Tinker-Board/
=> Add ASUS-TinkerBoardBasic model.

dtmi/ibase/ags102-1.json
iBase
https://www.ibase.com.tw/index.php
AGS102
https://www.ibase.com.tw/english/ProductDetail/EmbeddedComputing/AGS102
=> Add iBase-AGS102 model.

dtmi/hisense/hk570-1.json, dtmi/roseek/cheetah1-1.json
Hisense
http://hics.hisense.com/index.aspx
Roseek
http://www.roseek.com/en/index.html
HK570 
http://hics.hisense.com/harddetail/index.aspx?nodeid=1920
Cheetah1 
http://www.roseek.com/en/product/cheetah1.html
=> Add Hisense-HK570 and Roseek-Cheetah1 models.

dtmi/eurotech/asset_service-1.json, dtmi/eurotech/diagnostic_service-1.json, dtmi/eurotech/rg_10_12_6x-1.json
Signed-off-by: David Woodard <david.woodard@eurotech.com>
Eurotech
https://www.eurotech.com/en
ReliaGate 10-12-6x
https://www.eurotech.com/en/products/iot/multi-service-iot-edge-gateways/reliagate-10-12
Plug and Play certification for the device
=> Addition of device models for Eurotech Reliagate 10-12-6x.

dtmi/com/hms_networks/ewon_flexy_azure_connector_basic-1.json, dtmi/com/hms_networks/ewon_flexy_azure_connector_blank-1.json
HMS Networks
https://www.hms-networks.com/
HMS Networks Ewon Flexy
- with Azure Connector application installed
https://www.ewon.biz/products/ewon-flexy
=> Add HMS Ewon Flexy DTDL Models

dtmi/compal/pixsee/babycam-2.json, dtmi/compal/pixsee/environmentsettings-2.json, dtmi/compal/pixsee/indicatorstate-2.json, dtmi/compal/pixsee/smartdetection_area-2.json, dtmi/compal/pixsee/smartdetection_cry-2.json
Company Info
Compal electronics, inc.
https://www.compal.com/
IoT Plug and Play Device Info
Pixsee
https://www.pixseecare.com/en/
Model Submission Goals
Code Owners & Reserved Names
=> 2.0.0 DTDL Pixsee

dtmi/eurotech/diagnostic_service-2.json, dtmi/eurotech/rg_10_12_6x-2.json
Signed-off-by: David Woodard <david.woodard@eurotech.com>
Company Info
Eurotech
https://www.eurotech.com/en
IoT Plug and Play Device Info
ReliaGate 10-12-6x
https://www.eurotech.com/en/products/iot/multi-service-iot-edge-gateways/reliagate-10-12
Model Submission Goals
Update model to include internal modules.
Code Owners & Reserved Names
=> Update versions to support internal modules.

dtmi/com/hms_networks/ewon_flexy_azure_connector_starter-1.json
HMS Networks
https://www.hms-networks.com/
HMS Networks Ewon Flexy
- with Azure Connector application installed
https://www.ewon.biz/products/ewon-flexy
Add a corrected device model
=> Add Corrected Basic/Starter Flexy Model

dtmi/osconfig/deviceosconfiguration-1.json, dtmi/osconfig/deviceosconfiguration-2.json, dtmi/osconfig/networking-1.json
Signed-off-by: Marius Niculescu <mariusni@microsoft.com>
=> OSConfig: new Networking interface

dtmi/arbor/fpc8100-1.json
Arbor
https://www.arbor-technology.com/tw/Home
FPC-8100
https://www.arbor-technology.com/tw/Product/Pro/Model/FPC-8100_tw
=> Add Arbor-FPC8100

dtmi/eurotech/asset_service-2.json, dtmi/eurotech/diagnostic_service-3.json, dtmi/eurotech/rg_10_12_6x-3.json
Update models to include complete asset command response. Fix data types for diagnostic service.
Signed-off-by: David Woodard <david.woodard@eurotech.com>
Company Info
Eurotech
https://www.eurotech.com/en
IoT Plug and Play Device Info
ReliaGate 10-12-6x
https://www.eurotech.com/en/products/iot/multi-service-iot-edge-gateways/reliagate-10-12
Model Submission Goals
Update model to include internal modules.
Code Owners & Reserved Names
=> [Eurotech] Models update to support asset command response.

dtmi/asus/pe100a-1.json, dtmi/asus/pe200s-1.json, dtmi/asus/pe200u-1.json
ASUS
https://www.asus.com/tw
PE100A
https://www.asus.com/tw/networking-iot-servers/aiot-industrial-solution/all-series/pe100a/
PE200U
https://www.asus.com/tw/Networking-IoT-Servers/AIoT-Industrial-Solution/All-series/PE200U/
PE200S
https://www.asus.com/tw/networking-iot-servers/aiot-industrial-solution/all-series/pe200s/
harryliou from ASUS
=> Add ASUS-PE100A, ASUS-PE200U, ASUS-PE200S models.

dtmi/partner/audreyfamily-1.json
Partner
https://www.partner.com.tw/
AUDREY FAMILY
https://www.partner.com.tw/audrey-pos/
=> Add AUDREY FAMILY model.

dtmi/protech/se_n207-1.json
Protech
https://www.protech.com.tw/Home/home_us.asp
SE-N207
https://www.protech.com.tw/Products/product_us.asp?PM_ID=650
=> Add SE-N207 model.

dtmi/m5stack/deviceinformation-1.json
=> add m5stack

dtmi/adlink/cexpress_tl-1.json
ADLINK
https://www.adlinktech.com/en/index
cExpress-TL
https://www.adlinktech.com/Products/Computer_on_Modules/COMExpressType6/cExpress-TL?lang=en
=> Add  cExpress-TL model.

dtmi/seeedkk/wioterminal/wioterminal_co2checker-2.json
=> Update Add CO2 checker - Wio Terminal

dtmi/com/atmark_techno/armadillo/iot_gw_g3m1-1.json, dtmi/com/atmark_techno/armadillo/thermalsensor-1.json
Atmark Techno, Inc.
[https://www.atmark-techno.com/](https://www.atmark-techno.com/)
Armadillo-IoT GW G3M1
[https://armadillo.atmark-techno.com/armadillo-iot-g3](https://armadillo.atmark-techno.com/armadillo-iot-g3)
=> add Armadillo-IoT GW G3M1's device model

.azure-devops/sync_models.yml
- Uses new `dmr-client` beta.2 capability to expand a repo in place.
- Uses and publishes new `dmr-client` beta.2 index capability.
- Publishes `metadata.json` file.
=> New sync models functionality.

dtmi/m5stack/m5go-1.json
M5Stack
https://m5stack.com/
https://github.com/m5stack
freertos
Microsoft Azure IoT Device SDK for C
=> Add device M5GO

dtmi/seeedkk/wioterminal/wioterminal_accumulation_counter-1.json, dtmi/seeedkk/wioterminal/wioterminal_human_detection-1.json, dtmi/seeedkk/wioterminal/wioterminal_temp_humi-1.json
=> [seeedkk] Add 3 models

dtmi/posiflex/rt6015-1.json, dtmi/posiflex/xt7315-1.json
Posiflex
https://www.posiflex.com/en-global
JIVA_XT-7315
https://www.posiflex.com/en-global/product/index/pos-terminal/JIVA-XT/JIVA_XT-7315
RT-6015
https://www.posiflex.com/en-global/product/index/pos-terminal/RT-Series/RT-6015#specification
=> Add XT7315 model.

.github/workflows/validate_models.yml
- Upgrades the validation workflow to use the `1.0.0-beta.2` revision of DMR tools.
- More exciting changes to come in future iterations.
=> Upgrade to 1.0.0-beta.2 tools.

dtmi/aaeon/boxer_rk88-1.json
AAEON
https://www.aaeon.com/tw/
BOXER-RK88
Yangtate from AAEON
=> Add AAEON BOXER-RK88 model.

dtmi/com/bluebird/rt101-1.json, dtmi/com/bluebird/st102-1.json
* Add RT101 device model
* Add ST102 device model …
=> Add 2 device models

.azure-devops/sync_models.yml, .github/workflows/validate_models.yml
Updates the github and ADO workflows to use dmr-client beta.3
=> Update to use dmr-client beta3

dtmi/winmate/il20-1.json, dtmi/winmate/m101p-1.json
Winmate
https://www.winmate.com/
IL20
https://www.winmate.com/
=> Add IL20 model.

dtmi/seeedkk/reterminal/reterminal_aziot_example-1.json
Seeed K.K.
[Seeed reTerminal](https://www.seeedstudio.com/ReTerminal-with-CM4-p-4904.html)
* IoT PnP Device Certification
=> [seeedkk] Add the reterminal_aziot_example model

dtmi/seeedkk/reterminal/reterminal_aziot_example-2.json
Seeed K.K.
[Seeed reTerminal](https://www.seeedstudio.com/ReTerminal-with-CM4-p-4904.html)
* IoT PnP Device Certification
=> [seeedkk] Update the reterminal_aziot_example

dtmi/kartben/artificial_nose-1.json, dtmi/seeedstudio/grove/multichannel_gas_sensor_v2-1.json
=> Add models for TinyML artificial nose

dtmi/com/develcoproducts/homesafetysmokealarm-1.json, dtmi/com/develcoproducts/homesafetywindowsensor-1.json, dtmi/com/develcoproducts/smokealarm-1.json, dtmi/com/develcoproducts/windowsensor-1.json
=> develco PnP first bundles

dtmi/aaeon/boxer_rk88-2.json
=> Add BOXER-RK88 ver.2 model.

dtmi/seeedkk/wioterminal/wioterminal_watchdog_vl53l0x-1.json
=> [seeedkk] Add the wioterminal_watchdog_vl53l0x model

dtmi/seeedkk/wioterminal/wioterminal_watchdog-1.json
=> [seeedkk] Add the wioterminal_watchdog model

dtmi/seeedkk/wioterminal/wioterminal_dust-1.json
=> [seeedkk] Add the wioterminal_dust

dtmi/tartabit/assettracker-1.json
When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.
:star2: Please replace the markdown comment examples with your own values.
Tartabit, LLC
https://www.tartabit.com
github.com/tartabit
Used with the Tartabit IoT Bridge for LPWAN integration to Azure:
https://www.tartabit.com/overview
Needed for easy integration by our customers with easy reference to our model.
- @bocajim is owner
reserved name: tartabit
=> Add Tartabit Asset Tracker model

dtmi/seeedkk/wioterminal/wioterminal_digital_signage-1.json
=> [seeedkk] Add the wioterminal_digital_signage

dtmi/synnex/androiddeviceinfo-1.json
Synnex
http://www.synnex.com.tw/
General Device Information (Android)
=> Add Synnex androiddeviceinfo-1.json

dtmi/seeedkk/wioterminal/wioterminal_digital_signage-2.json
=> [seeedkk] Modify the wioterminal_digital_signage

dtmi/shuttle/d230-1.json
Shuttle 
http://global1.shuttle.com/
D230
http://global.shuttle.com/products/productsDetail?productId=2465
=> Add shuttle d230-1.json

dtmi/leetop/a203-1.json, dtmi/leetop/a501-1.json
Leetop
http://leetop.cn/
A501
http://leetop.cn/productinfo/323264.html
A203
http://leetop.cn/productinfo/323237.html
=> Add Leetop models.

dtmi/cclyun/apollo-1.json
CCLYUN
https://www.cclyun.com/
Apollo
https://www.cclyun.com/product/smart-pos-apollo.html
=> Add apollo-1.json

dtmi/hisense/hk500e-1.json, dtmi/hisense/hk560-1.json, dtmi/hisense/hk588-1.json
Hisense
http://hics.hisense.com/index.aspx
HK500E
HK560
HK588
=> Add Hisense models.

dtmi/avnet/AvnetMt3620G100-1.json, dtmi/avnet/mt3620_g100-1.json
- Avnet
- avnet.com
- https://github.com/Avnet
- [Avnet Azure Sphere Guardian 100](http://avnet.me/guardian100)
- Azure Sphere MCU
- Azure Sphere SDK
- Demo applications for Azure Sphere Workshop students
- @bawilless
=> Add Avnet Guardian 100 Model

dtmi/atmark_techno/armadillo/iot_gw_a6_doorsmonitor-3.json
Atmark Techno, Inc.
https://www.atmark-techno.com/
Armadillo-IoT GW A6 doors monitor configuration
https://armadillo.atmark-techno.com/armadillo-iot-a6
=> add Armadillo-IoT GW A6 DoorsMonitor's model v3

dtmi/asus/tinkeredger-2.json, dtmi/synnex/lprdetectcam-1.json
ASUS
https://www.asus.com/tw/
Tinker Edge R
https://tinker-board.asus.com/product/tinker-edge-r.html
=> Add LPR related models

dtmi/atmark_techno/cactusphere/cactusphere_basic-1.json
Atmark Techno, Inc.
https://www.atmark-techno.com/
Cactusphere
https://armadillo.atmark-techno.com/cactusphere
=> add Cactusphere Basic Version device model

dtmi/delta/linuxdeviceinfo-1.json, dtmi/delta/linuxdeviceinfo-2.json
=> add Delta LinuxDeviceInfo2

dtmi/fii/fii/badge_apt-1.json
- Company name: FII
- Company website: https://us.fiimart.com/web/nextiiot/
- Product website: https://tw.fiimart.com/web/nextiiot/SolutionPage/Index/PROD/82?culture=en-US
- Product website: https://tw.fiimart.com/web/nextiiot/Store/Detail/PLAN/90?culture=en-US
- Product website: https://tw.fiimart.com/web/nextiiot/Store/Detail/PROD/88?culture=en-US
- Product website: https://tw.fiimart.com/web/nextiiot/Store/Detail/PROD/106?culture=en-US
- Product website: https://tw.fiimart.com/web/nextiiot/Store/Detail/PROD/91?culture=en-US
=> Add Fii Badge_APT model file

dtmi/terasic/fcc/de10_nano-1.json, dtmi/terasic/fcc/de10_nano_sensor-1.json, dtmi/terasic/fcc/de10_nano_threshold-1.json, dtmi/terasic/fcc/rfs-1.json
Terasic https://www.terasic.com.tw/
FCC (FPGA Cloud Connectivity Kit) http://fcc.terasic.com.tw/
=> Add FCC models

dtmi/seeedkk/rebutton-1.json
Seeed K.K.
[Seeed ReButton](https://www.seeedstudio.com/ReButton-p-2930.html)
=> [seeedkk] Add the rebutton

dtmi/azureiot/devkit/freertos/esp32azureiotkit-1.json
=> Add Espressif ESP32 Azure IoT Kit model

dtmi/crl/guardian-3.json
=> add crl GUARDIAN model. 

dtmi/azure/phoneasiotdevice/application-2.json, dtmi/azure/phoneasiotdevice/sensors/accelerometer-2.json, dtmi/azure/phoneasiotdevice/sensors/gyroscope-1.json
Moves the gyroscope sensor to a new component
Updates accelerometer to remove the gyroscope
Updates application to use both new components
=> Update Paad model with new gyroscope component

dtmi/kr/co/mazetech/towncast/transmitter-2.json
- Company name: MazeTech
Towncast Transmitter device
- OS & Arch: Baremetal MCU
N/A
=> Add MazeTech transmitter interface

dtmi/azure/phoneasiotdevice/application-3.json
updates de component displayName to fix a typo
=> fix typo in gryroscope

dtmi/azurertos/devkit/gsgstml4s5-1.json
=> add stm l4s5 for azure rtos gsg

dtmi/eurotech/dg_10_12_6x-1.json, dtmi/eurotech/rg_10_14_3x-1.json
* ReliaGATE 10-14-6x
* DynaGATE 10-12-3x
Signed-off-by: David Woodard <david.woodard@eurotech.com>
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/cli …
=> Adding the following Eurotech device models:

dtmi/fibocom/devicemanagement/deviceinformation-1.json, dtmi/fibocom/ma510/pnp_sample-1.json
=> add interfaces of fibocom interface

dtmi/azurertos/devkit/gsgstml4s5-1.json, dtmi/azurertos/devkit/gsgstml4s5-2.json
=> Add the STM32 L4S5 Azure RTOS GSG v2 model

.azure-devops/sync_models.yml
=> Sync pipeline to support build pools and other enhancements.

dtmi/com/socomec/socomecdevice-1.json, dtmi/com/socomec/socomecgateway-1.json
=> First version of Socomec templates

dtmi/aimobile/jetsondeviceinformation-1.json, dtmi/aimobile/jetsonthermal_zones-1.json, dtmi/aimobile/m1_h3-1.json
=> add AIMobile M1-H3 model

.github/pull_request_template.md
=> UPDATE PR Template

dtmi/orgpal/palthree/palthree_demo_0-1.json
- Company name: Orgpal
- Company website: https://www.orgpal.com/
- GitHub presence: https://github.com/orgpal
- Product website: https://www.orgpal.com/palthree-iot-azure
- OS & Arch: [.NET …
=> Add new DTDL model for Orgpal PALTHREE

dtmi/atos/gateway/rtos_gateway-1.json, dtmi/atos/gateway/sphere_gateway-1.json
=> add a gateway

dtmi/tartabit/assettracker-2.json, dtmi/tartabit/generic-1.json, dtmi/tartabit/loraedgetracker-1.json
Tartabit, LLC
Used by Tartabit IoT Bridge for LPWA devices.
Used by Tartabit IoT Bridge for LPWA devices.
Tartabit
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct …
=> Added new models

dtmi/aitos/ad40-1.json, dtmi/aitos/as10-1.json
Company Info
AITOS Inc.
IoT Plug and Play Device Info
AS10 is a USB Key based on Azure Sphere chipset MediaTek MT3620AN. With Azure Sphere, AS10 can connect devices to Microsoft Azure Sphere IoT cloud securely and reliably， which makes the connected devices to be updated, controlled, …
=> Add new models

dtmi/azure/iot/deviceupdatecontractmodel-2.json, dtmi/azure/iot/deviceupdatemodel-2.json
=> Submit PNP models for Device Update GA

dtmi/azurertos/devkit/gsgmicrochipsame54-1.json
Microsoft
https://github.com/azure-rtos/getting-started
Azure RTOS
Microchip SAM E54
Azure RTOS GSG examples
@ryanwinter
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct …
=> add Microchip SAM E54 for Azure

.azure-devops/sync_models.yml
=> Parameterized dmr-client version.

dtmi/winmate/im20-1.json, dtmi/winmate/im20-2.json
**Belden Inc**
https://www.belden.com/
**Hirschmann OpEdge-8D**
[Hirschmann OpEdge-8D](https://www.belden.com/products/industrial-networking-cybersecurity/edge-devices/opedge-8d)
OS: Linux
Architecture: x86
**Model Submission Goal**
Hirschmann OpEdge-8D Device Certification for Azure …
=> Add OpEdge-8D model

dtmi/com/example/temperaturecontroller-4.json, dtmi/com/example/thermostat-4.json
=> Submit example PNP models for Device Update GA

dtmi/hattelandtechnology/hd08t30mmc-1.json, dtmi/hattelandtechnology/linuxdeviceinfo-1.json, dtmi/hattelandtechnology/windowsdeviceinfo-1.json
- Company name: Hatteland Technology AS
- Company website: www.hattelandtechnology.com
- Product website: https://www.hattelandtechnology.com/view_product?id=280!main_category=Marine%20&%20Offshore=
- OS & Arch: Windows IoT Enterprise
Device certification: Trusted platform module
> …
=> Add device model HD08T30MMC

dtmi/aaeon/up4000-1.json, dtmi/aaeon/upsquaredpro7000-1.json, dtmi/aaeon/upxtremei12-1.json
AAEON
UP Xtreme i12, UP Squared Pro 7000, UP 4000
> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.
This …
=> Add UP Xtreme i12, UP Squared Pro 7000, UP 4000 models

dtmi/kumhoelectric/smartmesh_gateway-1.json
- Company name : Kumho Electric
- Company website : https://www.khe.co.kr/en/
- Product website : https://www.khe.co.kr/en/
- OS & Arch : Azure Sphere
- SDK used for model implementation : Azure SDK
- Presence in the [Certified Device …
=> Add Kumho Electric SmartMesh Gateway PnP Model

.github/workflows/validate_models.yml
Update validate-models action used to 1.0.3
Tested in forked branch and verified work as expected
> Indicates GitHub alias entries to be added to the repo …
=> Update validate-models action used

dtmi/aaeon/ics_6280-1.json
AAEON
ICS-6280
> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.
This project has adopted the [Microsoft …
=> Add ICS-6280 model

dtmi/azure/iot/deviceupdate-2.json, dtmi/azure/iot/deviceupdatecontractmodel-3.json, dtmi/azure/iot/deviceupdatemodel-3.json
=> Submit PNP models for Device Update GA+

dtmi/eurotech/dg_10_14_3x-1.json
Added the following model file for the DynaGATE 10-14 edge gateway: dg_10_14_3x-1.json
Eurotech
[https://www.eurotech.com](https://www.eurotech.com/)
DynaGATE 10-14
[https://www.eurotech.com/products/dynagate-10-14/](https://www.eurotech.com/products/dynagate-10-14/)
=> [EUROTECH] Adding DynaGATE 10-14 model
