- .github/pull_request_template.md
- .github/workflows/push_expanded_to_storage.yml
- .github/workflows/validate_models.yml
This PR
- Improves the PR template format
- Keeps example data points as comments to prevent markdown render.
- Clarified some language.
- Ensure non-well formed model file placed in valid dtmi convention (with respect to the `dtmi/` directory) location will error
- See [this failure](https://github.com/digimaun/iot-plugandplay-models/pull/15/checks?check_run_id=1482341487) for example
- Ensure model file placed in a non-valid dtmi convention (with respect to the `dtmi/` directory) will error.
- See [this failure](https://github.com/digimaun/iot-plugandplay-models/pull/14/checks?check_run_id=1482333194) for example
PR Format example:
> Improve WF validation. Improve PR template.

- dtmi/nuvoton/numaker_iot_m487_dev-1.json
- dtmi/nuvoton/sensor_bmx055-1.json
- Company name: Nuvoton
- Company website: www.nuvoton.com
- GitHub presence: https://github.com/cyliangtw/iot-plugandplay-models
- Product website: http://www.nuvoton.com.cn/board/numaker-iot-m487/
- OS & Arch: Mbed OS, ARM Cortex-M4
- SDK used for model implementation: Azure-C-SDK
test-id: b9f2537a-6d07-49d9-9551-fe7e985fb355
log: attachment test log file
[iot-m487-log.txt](https://github.com/Azure/iot-plugandplay-models/files/5694321/iot-m487-log.txt)
@cyliangtw
> Nuvoton NuMaker-IoT-M487 Interface

- dtmi/adlink/ipismarcpx30-1.json
ADLINK
https://www.adlinktech.com/en/index
I-Pi SMARC PX30
https://www.ipi.wiki/pages/i-pi-smarc-px30
> Add ADLINK-IPiSMARCPx30 model.

- dtmi/asus/tinkerboard-1.json
ASUS
https://www.asus.com/tw/
Tinker Board
https://www.asus.com/tw/Single-Board-Computer/Tinker-Board/
> Add ASUS-TinkerBoard model.

- dtmi/sysinno/iaeris1-1.json
- dtmi/sysinno/iaeris1-2.json
- Company name: Sysinno Technology Inc.
- Company website : [https://www.sysinnotec.com/ehomepage](https://www.sysinnotec.com/ehomepage)
- Product pdf : [iAeris Indoor Air Quality Detector PDF](https://ac1f3ec5-3a86-4c35-9d2e-c0d4f323d127.filesusr.com/ugd/2f33a0_a7abe4d205c24ef995e6d5b4cc446ab6.pdf)
- MCU: Azure sphere
- Custom solution
@Lin-YenYu-sysinno
> Add factor of ozone into sysinno Air Quality Detector

- dtmi/jwipc/k065-1.json
JWIPC
http://www.jwipc.com/
K065
http://www.jwipc.com/pro/p43.html
> Add JWIPC-K065model.

- dtmi/com/deviceworx/xtag_ble_acc-1.json
Company name: Deviceworx
Company website: https://www.deviceworx.com/products_xtag_xgw.html
GitHub presence: https://github.com/TRUMPF-IoT/C-DEngine
Submission performed by C-Labs on behalf of Deviceworx
Product website: https://www.deviceworx.com/products_xtag_xgw.html
- Device certification (https://certify.azure.com/products/945f0fd7-d30f-4cdf-a4cb-974fa8b93010)
@MarkusHorstmann
@muenchris
mark@deviceworx.com (not on GitHub)
> Add model for DeviceWorx xTAG BLE Acceleration Sensor 

- dtmi/gigaipc/qbixprowhla8265hc2-1.json
GIGAIPC
http://www.gigaipc.com/
QBiX-Pro-WHLA8265H-C2
https://www.gigaipc.online/innodisk-qbix-pro
> Add QBiX-Pro-WHLA8265H-C2 model

- dtmi/com/deviceworx/xtag_usb_acc-1.json
Company name: Deviceworx
Company website: https://www.deviceworx.com/products_xtag_xgw.html
GitHub presence: https://github.com/TRUMPF-IoT/C-DEngine
Submission performed by C-Labs on behalf of Deviceworx
Product website: https://www.deviceworx.com/products_xtag_xgw.html
- Device certification (https://certify.azure.com/products/739b6a1c-72db-4ca4-b146-d052885c63fb)
@MarkusHorstmann
@muenchris
mark@deviceworx.com (not on GitHub)
> Add model for DeviceWorx XTAG USB Acceleration Sensor

- dtmi/osconfig/deviceosconfiguration-3.json
- dtmi/osconfig/firewall-1.json
Signed-off-by: Marius Niculescu <mariusni@microsoft.com>
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet#device-model-repository-client …
> New Firewall interface for OSConfig model

- dtmi/ted/e1000_ibs02pir2-1.json
- dtmi/ted/ibs02pir2-1.json
- dtmi/ted/x1000_ibs02pir2-1.json
> add new model e1000_ibs02pir2-1 and x1000_ibs02pir2-1

- dtmi/ted/e1000_ibs01t-1.json
- dtmi/ted/e1000_ibs03tp-1.json
- dtmi/ted/ibs01t-1.json
- dtmi/ted/ibs03tp-1.json
- dtmi/ted/x1000_ibs01t-1.json
- dtmi/ted/x1000_ibs03tp-1.json
> Add model e1000_ibs01t, e1000_ibs03tp, x1000_ibs01t, x1000_ibs03tp

- dtmi/ibase/mi996-1.json
> add iBase MI996 model

- dtmi/ecs/qc710-1.json
ECS
https://www.ecs.com.tw/
QC710
https://www.ecs.com.tw/en/Product/System/QC710/overview
> Add ECS-QC710 model.

- dtmi/avcon/mps_h-1.json
- dtmi/avcon/orc100-1.json
AVCON
http://www.avcon.com.cn/
ORC100
http://www.avcon.com.cn/product/detail.aspx?id=25
MPS-H
http://www.avcon.com.cn/product/detail.aspx?id=97
> Add AVCON models

- dtmi/com/microchip/sam_iot_wm-1.json
Initial submission of SAM_IoT_WM device model …
> SAM_IoT_WM Submission

- dtmi/redeye/redeye_1_plus-2.json
Taiwan RedEye Biomedical Inc.
[https://www.redeyebmi.com](https://www.redeyebmi.com)
[https://www.redeyebmi.com/product_detail.asp?id=1](https://www.redeyebmi.com/product_detail.asp?id=1)
Product name: RedEye Visible Spectrophotometer for clinical use
Model name: redeye 1 Plus
Model name of wireless charger: redeye-S
Trade Name: RedEye
Way of charging: 5V, 1A   (Wireless charging)
Place of production: Taiwan
Effective period: 5 years
Product content:   
◆   Handheld device
◆   Wireless Charger
◆   Filter consumables (1 box )
◆   Instruction for use
◆   Accessories for wall mount and base
Device Certification.
Use Banana-Pi-BPI-M64 on [Azure Certified Device catalog](https://devicecatalog.azure.com/devices/5cfad7c1-df2a-0086-bcc2-4d663178671d) as a gateway with provided image to connects …
> Add Redeye-1-Plus-V2

- dtmi/vecow/aic_100-1.json
> Add Vecow AIC-100 Model

- dtmi/aaeon/gene_whu6-1.json
- dtmi/aaeon/hardwaremonitor-1.json
1. Add hardware monitor interface that monitors temperature, fan speed and voltage.
2. Add GENE-WHU6 model.
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tre …
> Add AAEON Interfaces.

- .azure-devops/sync_models.yml
- .azure-devops/sync_models_azcopy.yml
- .github/pull_request_template.md
- .github/workflows/validate_models.yml
* Use beta5 for validation.
* Use beta5 (and switch to NuGet package) for publishing pipeline.
> Increment to dmr-client beta5

- dtmi/lab3/nexus-1.json
> Added NEXUS model

- .azure-devops/setup_cli.yml
- .azure-devops/sync_models.yml
- Supports pinned Az CLI install for scenarios where latest/pre-baked image version should not be used for reasons.
> Support pinned Az CLI install

- README.md
- Remove leading `>` from bash sections.
- Move comments in the bash sections outside of it.
I was following the readme and hit the copy icon that shows on mouse over (as usual) 
to then realize that it includes a leading `> `  to mimic the prompt. Some of these sections also included a comment at the top.
Both make the commands unusable when trying to use the speedy access of clicking on copy icon to just paste it at the prompt.
This PR addresses that by cleaning up the commands and make them usable with the shortcut.
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact …
> Improvements in readme to allow direct usage of tool commands

- dtmi/stmicroelectronics/b_u585i_iot02a/control_if-1.json
- dtmi/stmicroelectronics/b_u585i_iot02a/standard_fw-3.json
- dtmi/stmicroelectronics/b_u585i_iot02a/standard_if-2.json
> STMicroelectronics
> STM32 B_U585I_IOT02A
> Using release X-CUBE-AZURE 2.0.0 [package ](https://www.st.com/en/embedded-software/x-cube-azure.html)
> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be …
> stm32 b_u585i_iot02a device template v3

- dtmi/gigaipc/qbixplusehla6412a1-1.json
GIGAIPC
QBiX-Plus-EHLA6412-A1
> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.
> Add QBiX-Plus-EHLA6412-A1 model

- dtmi/murata/b_u585i_iot02a/control_if-1.json
- dtmi/murata/b_u585i_iot02a/demo_iot-1.json
- dtmi/murata/b_u585i_iot02a/standard_fw-1.json
- dtmi/murata/b_u585i_iot02a/standard_fw-3.json
- dtmi/murata/b_u585i_iot02a/standard_if-1.json
- dtmi/murata/b_u585i_iot02a/standard_if-2.json
- dtmi/murata/demo_iot-1.json
> Murata IoT Device Models
